apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  selector:
    matchLabels:
      app: story
  replicas: 1
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: sysoiev/kub_docker_compose_spring_web:1
      volumes:
        - name: story-volume
          emptyDir: {}